name: homelab

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --accesslog=true
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge
      - observability

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus:/prometheus
    networks:
      - observability
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.local`)
      - traefik.http.routers.prometheus.entrypoints=web
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - edge
      - observability
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.local`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./volumes/loki:/loki
    networks:
      - observability
    labels:
      - traefik.enable=true
      - traefik.http.routers.loki.rule=Host(`loki.local`)
      - traefik.http.routers.loki.entrypoints=web
      - traefik.http.services.loki.loadbalancer.server.port=3100

networks:
  edge:
    driver: bridge
  observability:
    driver: bridge
